FORMAT: 1A
HOST: http://ico-dashboard:3000/

# Jincor ICO dashboard backend

Almost all operations require 2-factor Authentication.
To fulfill this requirement most of them are split to 2 endpoints: first (e.g. /user/login/initiate)
initiates login and generates JWT token. Next this token must be verified using endpoint /user/login/verify.

## Register user [/user]

User's email must be verified after registration. Next step after calling this endpoint is `POST /user/activate` using `verification.id` from response.

### Register new user [POST]

+ email `test@test.com` (string, required, email)
+ password `passwordA6` (string, required, min: 6, regex: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{6,}$)
+ name `ICO investor` (string, required, min: 3)
+ agreeTos `true` (boolean, equals: true)
+ referral `referral@test.com` (optional, string, base64 encoded email)

+ Request (application/json)

        {
            "email": "ortgma@gmail.com",
            "name": "ICO investor",
            "password": "test12A6!@#$%^&*()_-=+|/",
            "referral": "dGVzdEB0ZXN0LmNvbQ",
            "agreeTos": true
        }

+ Response 200 (application/json)

        {
            "id": "fb10d98f-2a5e-430d-bf2a-c76b42259b74",
            "email": "ortgma@gmail.com",
            "name": "ICO investor",
            "agreeTos": true,
            "verification": {
                "id": "3ed09e0a-72e1-417b-a05c-f0f08a5e1ffa",
                "method": "email"
            },
            "isVerified": false,
            "defaultVerificationMethod": "email",
            "referralCode": "b3J0Z21hQGdtYWlsLmNvbQ",
            "referral": "test@test.com"
        }

## Activate a user [/user/activate]

This endpoint response with JWT token so user can be immediately redirected to dashboard.
JWT token received by `/activate` DOES NOT require verification.
This endpoint's response also contains VERY important information: mnemonic phrase and private key of
user's ethereum address. This information should be saved by user. If user loses this he will also LOSE
access to his wallet of ICO dashboard.

### Activate a user [POST]

+ email `test@test.com` (string, required, email)
+ verificationId `bb38971-1f22-4f99-a904-62fb44430ab4` (string, required)
+ code `123456` (string, required)

+ Request (application/json)

        {
            "email": "test@test.com",
            "verificationId": "5bb38971-1f22-4f99-a904-62fb44430ab4",
            "code": "327845"
        }

+ Response 200 (application/json)

        {
            "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhYTQzMzA0LTNhMTEtNDNkNy05NjNhLTRmNDA0OTY2MDVmMyIsImxvZ2luIjoidGVzdEB0ZXN0LmNvbSIsImRldmljZUlkIjoiZGV2aWNlIiwianRpIjoiM2FhNDMzMDQtM2ExMS00M2Q3LTk2M2EtNGY0MDQ5NjYwNWYzZGV2aWNlMTUwNzcxOTg1MDMzMiIsImlhdCI6MTUwNzcxOTg1MDMzMiwic3ViIjoiNWJiMzg5NzEtMWYyMi00Zjk5LWE5MDQtNjJmYjQ0NDMwYWI0IiwiYXVkIjoiamluY29yLmNvbSIsImV4cCI6MTUwNzcyMDQ1NTEzMn0.kG-XjH4fCcCY90dXEOND1UPawegsaJJ5WA8myDXw7Y4",
            "mnemonic": "phrase",
            "privateKey": "key",
            "wallets": [
                {
                    "ticker": "ETH",
                    "address": "0x7Ec2173e79dbFd4cab0A507D1c11B0E25fA2F404",
                    "balance": "0"
                }
            ],
        }

## Initiate login [/user/login/initiate]

The accessToken got from this endpoint response MUST BE ALWAYS verified via `/user/login/verify`.
Authentication attempts with not verified token will result in 401 response.

### Initiate login [POST]

+ email `test@test.com` (string, required, email)
+ password `passwordA6` (string, required)

+ Request (application/json)

        {
            "email": "test@test.com",
            "password": "test12A6!@#$%^&*()_-=+|/"
        }

+ Response 200 (application/json)

        {
            "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhYTQzMzA0LTNhMTEtNDNkNy05NjNhLTRmNDA0OTY2MDVmMyIsImxvZ2luIjoidGVzdEB0ZXN0LmNvbSIsImRldmljZUlkIjoiZGV2aWNlIiwianRpIjoiM2FhNDMzMDQtM2ExMS00M2Q3LTk2M2EtNGY0MDQ5NjYwNWYzZGV2aWNlMTUwNzcxOTg1MzcwNiIsImlhdCI6MTUwNzcxOTg1MzcwNiwic3ViIjoiNWJiMzg5NzEtMWYyMi00Zjk5LWE5MDQtNjJmYjQ0NDMwYWI0IiwiYXVkIjoiamluY29yLmNvbSIsImV4cCI6MTUwNzcyMDQ1ODUwNn0.vaZtMpPlPZDSLCVpMMC2dpCvbSram9mXNBPAaxSupKc",
            "isVerified": false,
            "verification": {
                "verificationId": "7fa96769-7bcc-4705-b544-02a83707cfc8",
                "consumer": "test@test.com",
                "expiredOn": 1507720153,
                "status": 200,
                "method": "email"
            }
        }

## Verify login [/user/login/verify]

+ accessToken `token` (required, string)
+ verification
    + id (string, required)
    + code (string, required)
    + method (string, required)

### Verify login [POST]

+ Request (application/json)

        {
            "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhYTQzMzA0LTNhMTEtNDNkNy05NjNhLTRmNDA0OTY2MDVmMyIsImxvZ2luIjoidGVzdEB0ZXN0LmNvbSIsImRldmljZUlkIjoiZGV2aWNlIiwianRpIjoiM2FhNDMzMDQtM2ExMS00M2Q3LTk2M2EtNGY0MDQ5NjYwNWYzZGV2aWNlMTUwNzcxOTg1MzcwNiIsImlhdCI6MTUwNzcxOTg1MzcwNiwic3ViIjoiNWJiMzg5NzEtMWYyMi00Zjk5LWE5MDQtNjJmYjQ0NDMwYWI0IiwiYXVkIjoiamluY29yLmNvbSIsImV4cCI6MTUwNzcyMDQ1ODUwNn0.vaZtMpPlPZDSLCVpMMC2dpCvbSram9mXNBPAaxSupKc",
            "verification": {
                "id": "7fa96769-7bcc-4705-b544-02a83707cfc8",
                "code": "544188",
                "method": "email"
            }
        }

+ Response 200 (application/json)

        {
            "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhYTQzMzA0LTNhMTEtNDNkNy05NjNhLTRmNDA0OTY2MDVmMyIsImxvZ2luIjoidGVzdEB0ZXN0LmNvbSIsImRldmljZUlkIjoiZGV2aWNlIiwianRpIjoiM2FhNDMzMDQtM2ExMS00M2Q3LTk2M2EtNGY0MDQ5NjYwNWYzZGV2aWNlMTUwNzcxOTg1MzcwNiIsImlhdCI6MTUwNzcxOTg1MzcwNiwic3ViIjoiNWJiMzg5NzEtMWYyMi00Zjk5LWE5MDQtNjJmYjQ0NDMwYWI0IiwiYXVkIjoiamluY29yLmNvbSIsImV4cCI6MTUwNzcyMDQ1ODUwNn0.vaZtMpPlPZDSLCVpMMC2dpCvbSram9mXNBPAaxSupKc",
            "isVerified": true,
            "verification": {
                "verificationId": "7fa96769-7bcc-4705-b544-02a83707cfc8",
                "consumer": "test@test.com",
                "expiredOn": 1507720153,
                "status": 200,
                "method": "email"
            }
        }
