FROM mhart/alpine-node:8.6

RUN mkdir -p /usr/src/app
ADD . /usr/src/app

WORKDIR /usr/src/app

RUN cp -r src/certs dist/

RUN apk add --update --no-cache git python make g++ && \
    npm install && \
    npm run build && \
    npm prune --production && \
    apk del --purge git python make g++ && \
    rm -rf ./src

CMD npm run serve