version: '2'
services:
  ico:
    image: registry.jincor.com/backend/ico-stage:latest
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
      - 443:4000
    links:
      - auth
      - redis
      - verify
      - rpc
    depends_on:
      - rpc
      - mongo
    restart: always
    networks:
      default:
        ipv4_address: 10.100.0.2

  auth:
    image: jincort/backend-auth:production
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
      JWT_KEY: "uZrJ!xe*xN?!;oU.u*;QOSM+|=4C?WH?6eWPcK/6AkIXIVGQguSA*r"
      THROTTLER_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
      TENANT_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
    ports:
      - "3000"
      - "4000"
    links:
      - redis
    networks:
      default:
        ipv4_address: 10.100.0.3

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
    volumes:
      - ./storage/redis:/data
    networks:
      default:
        ipv4_address: 10.100.0.4

  rpc:
    image: registry.jincor.com/backend/parity-rpc-ropsten:latest
    build:
      context: ./
      dockerfile: rpc.ropsten.Dockerfile
    ports:
      - "8546"
    volumes:
      - /root/parity:/root/.local/share/io.parity.ethereum
    restart: always
    networks:
      default:
        ipv4_address: 10.100.0.5

  verify:
    image: jincort/backend-verify:dev-62b3a0d
    environment:
      REDIS_URL: 'redis://redis:6379'
      THROTTLER_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
    links:
      - auth
      - redis
    networks:
      default:
        ipv4_address: 10.100.0.6

  mongo:
    image: registry.jincor.com/backend/mongodb:latest
    volumes:
        - ./storage/mongodb:/data/db
    networks:
      default:
        ipv4_address: 10.100.0.7
    ports:
      - "27017"
      - "28017"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1